### ISSUE TITLE
add support for migrating existing members

### ISSUE THREAD

**Issue by braaar** [HacklabJKL/mulysa#9]
One question here is how we deal with their history from the existing system.

To begin with, we want to import the member personalia only (name, contact info, etc.).
The membership type and status, financial history, etc. Should be handled in a separate migration. 

The current import script expects data in this format:

```
,,1,Firstname Lastname,email@example.com,2022-03-20,Jyvaskyla,muumi,0441231231,,,,,
kenttaNumero0,kenttaNumero1,kenttaNumero2,nimi1 nimi2,shko@pos.ti,2022-03-20,kenttaNumero6,kenttaNumero7,0445555555,kenttaNumero9,kenttaNumero10,kenttaNumero11,kenttaNumero12,kenttaNumero13
kenttaNumero0,kenttaNumero1,kenttaNumero2,nimi1 nimi2,shko@pos.ti,2022-03-20,municipality,nick,0445555555,kenttaNumero9,kenttaNumero10,kenttaNumero11,kenttaNumero12,kenttaNumero13
```

**Tasks**
- [ ] Write script that exports data from our old system to a CSV file with the format seen above
- [ ] Ensure that mulysa has all the fields that we want in the user data model
  - [ ] #6 
  - [ ] #7  
- [ ] Modify mulysa migration script to read fields

**Comment by braaar** [comment]
The desired CSV format can be seen in a spreadsheet here:
https://docs.google.com/spreadsheets/d/13yEKo9TAagfATAd5cQUsiAwiZGKrz51WRzi-nS-JbpY/edit#gid=0
